import polars as pl
import json
import os
import time
import sys

def main():
    print("=== Phase 1: Evaluating Blocking / Candidate Generation ===")
    t0 = time.time()
    
    gt_file = 'dataset/normalized/train_ground_truth_pairs.parquet'
    cands_file = 'outputs/candidate_pairs_train_sample.tsv'
    sample_ids_file = 'outputs/s1_sample_ids.txt'
    
    if not os.path.exists(cands_file):
        print(f"Error: {cands_file} not found.")
        sys.exit(1)
        
    print("Loading Candidates...")
    cands = pl.read_csv(cands_file, separator='\t')
    n_cands = len(cands)
    
    print("Loading Ground Truth and Filtering by Sample...")
    gt_all = pl.read_parquet(gt_file)
    
    if os.path.exists(sample_ids_file):
        with open(sample_ids_file, 'r') as f:
            sampled_ids = set(line.strip() for line in f if line.strip())
        gt = gt_all.filter(pl.col("source1_entity_id").is_in(list(sampled_ids)))
    else:
        gt = gt_all
        
    n_gt = len(gt)
    
    print(f"Evaluating Recall on {n_gt} GT pairs (Sampled S1)...")
    # Evaluate recall
    rec_all = gt.join(cands, left_on=['source1_entity_id', 'matched_id'], right_on=['source1_entity_id', 'candidate_entity_id'], how='inner')
    n_recalled = len(rec_all)
    recall = n_recalled / n_gt if n_gt > 0 else 0
    
    print(f"Total Candidates: {n_cands:,}")
    print(f"Recall: {n_recalled:,} / {n_gt:,} ({recall*100:.4f}%)")
    
    # Candidate Statistics
    print("Computing Candidate Statistics...")
    cand_counts = cands.group_by('source1_entity_id').len().rename({'len': 'cand_count'})
    avg_cands = cand_counts['cand_count'].mean()
    max_cands = cand_counts['cand_count'].max()
    s1_entities_with_cands = len(cand_counts)
    
    pass_counts = cands.group_by('n_passes').len().sort('n_passes')
    pass_dist = {str(row['n_passes']): row['len'] for row in pass_counts.iter_rows(named=True)}
    
    stats = {
        "total_candidate_pairs": n_cands,
        "average_candidates_per_s1": float(avg_cands),
        "max_candidates_per_s1": int(max_cands),
        "s1_entities_with_candidates": s1_entities_with_cands,
        "passes_distribution": pass_dist
    }
    
    with open('outputs/candidate_statistics.json', 'w') as f:
        json.dump(stats, f, indent=4)
        
    report = {
        "dataset_size": {
            "ground_truth_pairs": n_gt,
        },
        "blocking_performance": {
            "recall": float(recall),
            "recalled_pairs": n_recalled,
            "missed_pairs": n_gt - n_recalled,
        },
        "candidate_pool": stats
    }
    
    with open('outputs/blocking_report.json', 'w') as f:
        json.dump(report, f, indent=4)
        
    print("Identifying Hard Misses...")
    # Hard misses are GT pairs not in candidates
    misses = gt.join(cands, left_on=['source1_entity_id', 'matched_id'], right_on=['source1_entity_id', 'candidate_entity_id'], how='anti')
    print(f"Found {len(misses):,} hard misses.")
    
    # Save hard misses
    misses.write_csv('outputs/hard_misses.csv')
    
    # Generate Phase 1 Report MD
    md_content = f"""# Phase 1: Blocking and Candidate Generation Report

## 1. Overview
The goal of Phase 1 is to maximize the true-match recall while keeping the candidate set size computationally feasible. We applied a simplified deterministic multi-pass blocking strategy using vectorized Polars joins, abandoning complex TF-IDF token inverted indexes to improve speed and memory efficiency.

## 2. Methodology
We executed 5 simple blocking passes relying on `country` as a strict partition:
- **Pass A**: `country` + exact `norm_name_clean`
- **Pass B**: `country` + name `prefix4` (first 4 characters of name without spaces)
- **Pass C**: `country` + significant name token (each word $\ge$ 3 chars minus stop words)
- **Pass D**: `country` + `postal_code` + significant name token
- **Pass E**: `country` + address digit (house number) + significant name token

Candidates are generated by a union across all these passes.

## 3. Results
- **Ground Truth Pairs:** {n_gt:,}
- **Total Candidate Pairs Generated:** {n_cands:,}
- **Recall:** {recall*100:.4f}% ({n_recalled:,} / {n_gt:,})
- **Average Candidates per S1:** {avg_cands:.1f}
- **Max Candidates per S1:** {max_cands:,}
- **S1 Entities matched with $\ge 1$ candidate:** {s1_entities_with_cands:,}

### Pass Trigger Distribution (Number of Passes matched)
"""
    for passes, count in pass_dist.items():
        md_content += f"- **{passes} Passes:** {count:,} candidate pairs\n"

    md_content += f"""
## 4. Hard Misses Analysis
We identified {len(misses):,} ground truth pairs that were not recalled by the multi-pass blocking strategy. These have been exported to `outputs/hard_misses.csv` for further analysis in Phase 2.

*Report generated automatically by src/evaluate_blocking.py in {time.time()-t0:.2f}s*
"""
    
    with open('outputs/PHASE1_REPORT.md', 'w') as f:
        f.write(md_content)
        
    print(f"Evaluation completed in {time.time()-t0:.2f}s. Artifacts saved in outputs/ directory.")

if __name__ == "__main__":
    main()
